project_id = "zhfibzpgabqgqgixgisk"

[functions.share]
verify_jwt = false

[functions.accept_share]
verify_jwt = false

[functions.workspace_snapshot]
verify_jwt = false

[functions.payuni_webhook]
verify_jwt = false

[functions.payuni_return]
verify_jwt = false

[functions.payuni_checkout]
verify_jwt = false
